# Generated by Django 2.2.1 on 2020-02-17 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URLCurta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=30, unique=True)),
                ('destino', models.URLField()),
                ('acessos', models.PositiveIntegerField(default=0)),
                ('data_criacao', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
